A bit more tests

diff --git a/git-shard b/git-shard
--- a/git-shard
+++ b/git-shard
@@ -6,21 +6,18 @@ set -euo pipefail
 if [ -n "${GIT_SHARD_DEBUG:-}" ]; then
 	# Bash errors handler
 	function errexit() {
-	  local err=$?
-	  set +o xtrace
-	  local code="${1:-1}"
-	  echo "Error in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}. '${BASH_COMMAND}' exited with status $err"
-	  # Print out the stack trace described by $function_stack
-	  if [ ${#FUNCNAME[@]} -gt 2 ]
-	  then
-	    echo "Call tree:"
-	    for ((i=1;i<${#FUNCNAME[@]}-1;i++))
-	    do
-	      echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
-	    done
-	  fi
-	  echo "Exiting with status ${code}"
-	  exit "${code}"
+		local err=$?
+		set +o xtrace
+		local code="${1:-1}"
+		echo "Error in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}. '${BASH_COMMAND}' exited with status $err"
+		# Print out the stack trace described by $function_stack
+		if [ ${#FUNCNAME[@]} -gt 2 ]; then
+			echo "Call tree:"
+			for ((i=1;i<${#FUNCNAME[@]}-1;i++)); do
+				echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
+			done
+		fi
+		exit "${code}"
 	}
 	trap 'errexit' ERR
 	set -o errtrace
