Make the error handler optional

diff --git a/git-shard b/git-shard
--- a/git-shard
+++ b/git-shard
@@ -2,31 +2,29 @@
 # shellcheck disable=SC2155
 
 set -euo pipefail
-# set -x
 
-
-# Bash errors handler
-function errexit() {
-  local err=$?
-  set +o xtrace
-  local code="${1:-1}"
-  echo "Error in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}. '${BASH_COMMAND}' exited with status $err"
-  # Print out the stack trace described by $function_stack
-  if [ ${#FUNCNAME[@]} -gt 2 ]
-  then
-    echo "Call tree:"
-    for ((i=1;i<${#FUNCNAME[@]}-1;i++))
-    do
-      echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
-    done
-  fi
-  echo "Exiting with status ${code}"
-  exit "${code}"
-}
-trap 'errexit' ERR
-set -o errtrace
-
-
+if [ -n "${GIT_SHARD_DEBUG:-}" ]; then
+	# Bash errors handler
+	function errexit() {
+	  local err=$?
+	  set +o xtrace
+	  local code="${1:-1}"
+	  echo "Error in ${BASH_SOURCE[1]}:${BASH_LINENO[0]}. '${BASH_COMMAND}' exited with status $err"
+	  # Print out the stack trace described by $function_stack
+	  if [ ${#FUNCNAME[@]} -gt 2 ]
+	  then
+	    echo "Call tree:"
+	    for ((i=1;i<${#FUNCNAME[@]}-1;i++))
+	    do
+	      echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}(...)"
+	    done
+	  fi
+	  echo "Exiting with status ${code}"
+	  exit "${code}"
+	}
+	trap 'errexit' ERR
+	set -o errtrace
+fi
 
 
 MAINREPO=$(git rev-parse --show-toplevel)
